DROP TABLE CLOTH;
DROP TABLE CLOTH_CATAGORY;
DROP TABLE CATAGORY_PER_CLOTH;
DROP SEQUENCE SEQ_CLNO;
DROP SEQUENCE SEQ_CATAPERCLNO;

--테이블 생성 & 제약조건 추가

DROP TABLE "CLOTH";

CREATE TABLE "CLOTH" (
    "NO"    NUMBER PRIMARY KEY,
	"CLOTH_ID"	VARCHAR2(10)		NOT NULL,
	"PHOTO_ID"	VARCHAR2(10)		NOT NULL,
	"NAME"	VARCHAR2(50)		NULL,
	"CREATED_DATE"	DATE		NOT NULL,
	"MORE_DETAIL"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "CLOTH"."CLOTH_ID" IS '의류ID';

COMMENT ON COLUMN "CLOTH"."PHOTO_ID" IS '사진번호';

COMMENT ON COLUMN "CLOTH"."NAME" IS '등록명';

COMMENT ON COLUMN "CLOTH"."CREATED_DATE" IS '등록일자';

COMMENT ON COLUMN "CLOTH"."MORE_DETAIL" IS '특이사항';

CREATE SEQUENCE SEQ_CLNO;

DROP TABLE "CLOTH_CATAGORY";

CREATE TABLE "CLOTH_CATAGORY" (
	"CLOTH_CODE"	VARCHAR2(5)		NOT NULL,
	"CLOTH_CATAGORY"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "CLOTH_CATAGORY"."CLOTH_CODE" IS '분류코드';

COMMENT ON COLUMN "CLOTH_CATAGORY"."CLOTH_CATAGORY" IS '종류명';

DROP TABLE "CATAGORY_PER_CLOTH";

CREATE TABLE "CATAGORY_PER_CLOTH" (
    "NO" NUMBER PRIMARY KEY,
	"CLOTH_ID"	VARCHAR2(10)		NOT NULL,
	"CLOTH_CODE"	VARCHAR2(5)		NOT NULL
);

COMMENT ON COLUMN "CATAGORY_PER_CLOTH"."CLOTH_ID" IS '의류ID';

COMMENT ON COLUMN "CATAGORY_PER_CLOTH"."CLOTH_CODE" IS '분류코드';

CREATE SEQUENCE SEQ_CATAPERCLNO;



-- 제약조건


--ALTER TABLE "CLOTH" ADD CONSTRAINT "FK_IMAGE_TO_CLOTH_1" FOREIGN KEY (
--	"PHOTO_ID"
--)
--REFERENCES "IMAGE" (
--	"ID"
--);

ALTER TABLE "CATAGORY_PER_CLOTH" ADD CONSTRAINT "FK_CATAPERCL_CI" FOREIGN KEY (
	"CLOTH_ID"
)
REFERENCES "CLOTH" (
	"NO"
);

ALTER TABLE "CATAGORY_PER_CLOTH" ADD CONSTRAINT "FK_CATAPERCL_CC" FOREIGN KEY (
	"CLOTH_CODE"
)
REFERENCES "CLOTH_CATAGORY" (
	"CLOTH_CODE"
);


ALTER TABLE "CLOTH" MODIFY (CREATED_DATE DEFAULT SYSDATE);


-- NOTNULL 제약조건 이름바꾸기( 원 제약조건명이 다를 수 있음!!)

--ALTER TABLE "CLOTH" RENAME CONSTRAINT "SYS_C007435" TO "NN_CLOTH_CLOTH_ID";
--
--
--ALTER TABLE "CLOTH" RENAME CONSTRAINT "SYS_C007436" TO "NN_CLOTH_PHOTO_ID";
--
--
--ALTER TABLE "CLOTH" RENAME CONSTRAINT "SYS_C007437" TO "NN_CLOTH_CREATED_DATE";
--
--
--ALTER TABLE "CATAGORY_PER_CLOTH" RENAME CONSTRAINT "SYS_C007440" TO "NN_CATAPERCL_CLOTH_ID";
--
--
--ALTER TABLE "CATAGORY_PER_CLOTH" RENAME CONSTRAINT "SYS_C007441" TO "NN_CATAPERCL_CLOTH_CODE";
--
--
--ALTER TABLE "CLOTH_CATAGORY" RENAME CONSTRAINT "SYS_C007438" TO "NN_CLOCATA_CLOTH_CODE";
--
--
--ALTER TABLE "CLOTH_CATAGORY" RENAME CONSTRAINT "SYS_C007439" TO "NN_CLOCATA_CLOTH_CATAGORY";



-- 데이터 입력

-- 의류 카테고리 분류

-- 대분류  : 상의(T0) / 하의(P0) / 잡화(S0) / 악세서리(AO) 


INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('T0', '상의');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('P0', '하의');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S0', '잡화');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('A0', '악세서리');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('T1', '아우터');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('P1', '바지');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('T2', '원피스');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('P3', '스커트');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S1', '가방');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S2', '신발');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S3', '스니커즈');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('A1', '시계');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S4', '모자');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('S5', '양말/레그웨어');
INSERT INTO CLOTH_CATAGORY (CLOTH_CODE, CLOTH_CATAGORY) VALUES('A2', '안경');



-- TEST 의류 생성

INSERT INTO CLOTH (NO, CLOTH_ID, PHOTO_ID, NAME, CREATED_DATE, MORE_DETAIL) VALUES(SEQ_CLNO.NEXTVAL, 'CL0000', 'CLPH0000', 'TESTCLOTH1', DEFAULT, NULL);
INSERT INTO CLOTH (NO, CLOTH_ID, PHOTO_ID, NAME, CREATED_DATE, MORE_DETAIL) VALUES(SEQ_CLNO.NEXTVAL, 'CL0001', 'CLPH0001', 'TESTCLOTH2', DEFAULT, NULL) ;


