--테이블 생성 & 제약조건 추가
DROP TABLE "CLOTH_PHOTO";

DROP TABLE "CATEGORY_PER_CLOTH";

DROP TABLE "CLOTH_CATEGORY";

DROP SEQUENCE SEQ_CLNO;

DROP SEQUENCE SEQ_CLPH;

CREATE TABLE "CLOTH_CATEGORY" (
    "CLOTH_CODE"     VARCHAR2(5) PRIMARY KEY NOT NULL,
    "CLOTH_CATEGORY" VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN "CLOTH_CATEGORY"."CLOTH_CODE" IS
    '분류코드';

COMMENT ON COLUMN "CLOTH_CATEGORY"."CLOTH_CATEGORY" IS
    '종류명';

CREATE TABLE "CATEGORY_PER_CLOTH" (
    "CLOTH_NO"   NUMBER NOT NULL,
    "CLOTH_CODE" VARCHAR2(5) NOT NULL
);

COMMENT ON COLUMN "CATEGORY_PER_CLOTH"."CLOTH_NO" IS
    '의류ID';

COMMENT ON COLUMN "CATEGORY_PER_CLOTH"."CLOTH_CODE" IS
    '분류코드';

ALTER TABLE CATEGORY_PER_CLOTH ADD CONSTRAINT FK_CATAPERCL_CN FOREIGN KEY ( CLOTH_NO )
    REFERENCES CLOTH;

ALTER TABLE CATEGORY_PER_CLOTH ADD CONSTRAINT FK_CATAPERCL_CC FOREIGN KEY ( CLOTH_CODE )
    REFERENCES CLOTH_CATEGORY;

CREATE TABLE "CLOTH_PHOTO" (
    "NO"            NUMBER NOT NULL,
    "CLOTH_NO"      NUMBER NOT NULL,
    "ORIGINAL_NAME" VARCHAR2(100) NOT NULL,
    "PHOTO_ID"      VARCHAR2(200)  NOT NULL,
    "CREATED_DATE"  DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN "CLOTH_PHOTO"."NO" IS
    '의류사진번호';

COMMENT ON COLUMN "CLOTH_PHOTO"."CLOTH_NO" IS
    '의류NO';

COMMENT ON COLUMN "CLOTH_PHOTO"."ORIGINAL_NAME" IS
    '파일원래이름';

COMMENT ON COLUMN "CLOTH_PHOTO"."PHOTO_ID" IS
    '파일변경이름(RENAMED)';

COMMENT ON COLUMN "CLOTH_PHOTO"."CREATED_DATE" IS
    '생성일자';

ALTER TABLE "CLOTH_PHOTO" ADD CONSTRAINT "PK_CLOTH_PHOTO" PRIMARY KEY ( "NO" );

ALTER TABLE "CLOTH_PHOTO"
    ADD CONSTRAINT "FK_CLOTHPH_CLOTH" FOREIGN KEY ( "CLOTH_NO" )
        REFERENCES "CLOTH" ( "NO" );

CREATE SEQUENCE SEQ_CLPH;

-- 제약조건

-- 데이터 입력

-- 의류 카테고리 분류
-- 대분류  : 상의(T0) / 하의(P0) / 잡화(S0) / 악세서리(AO) 

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    '00',
    '지정안함'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'T0',
    '상의'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'P0',
    '하의'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S0',
    '잡화'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'A0',
    '악세서리'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'T1',
    '아우터'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'P1',
    '바지'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'T2',
    '원피스'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'P3',
    '스커트'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S1',
    '가방'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S2',
    '신발'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S3',
    '스니커즈'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'A1',
    '시계'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S4',
    '모자'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'S5',
    '양말/레그웨어'
);

INSERT INTO CLOTH_CATEGORY (
    CLOTH_CODE,
    CLOTH_CATEGORY
) VALUES (
    'A2',
    '안경'
);

COMMIT;